version: '3.1' 

services:
  vscode-docker-vnc:
    container_name: vscode-docker-vnc
    image: openkbs/vscode-docker-vnc
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - CONTAINER_NAME=vscode-docker-vnc
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      # - APP_HOME=${APP_HOME:-/home/developer/app}
      # - APP_MAIN=${APP_MAIN:-setup.sh}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP:-192.168.0.160}
      - DOCKER_HOST_NAME=${DOCKER_HOST_NAME:-solar01}
      # ==== X11 Use only ====
      #- DISPLAY=$DISPLAY
      #- DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      # ==== vnc/no-vnc ====
      - WINDOW_MANAGER=xfce 
      - VNC_RESOLUTION=1280x800 
      - VNC_PW=vncpassword 
      # ==== code / code-server ====
      # The type of authentication to use. [password, none]
      - CODE_AUTH=${CODE_AUTH:-none}
      # If CODE_AUTH=none, this will be ignored
      - CODE_PASSWORD=${CODE_PASSWORD:-codepassword}
      - CODE_BIND_ADDR=0.0.0.0
    volumes:
      ## ==== Common mapping ====
      - /etc/hosts:/etc/hosts
      - /dev/shm:/dev/shm 
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix
      #- ./certificates:/home/developer/certificates
      ## ==== Use $HOME/data-docker as base directory: ====
      #- $HOME/data-docker/knime-vnc-docker/app:/home/developer/app
      #- $HOME/data-docker/knime-vnc-docker/data:/home/developer/data
      #- $HOME/data-docker/knime-vnc-docker/workspace:/home/developer/workspace
      #- $HOME/data-docker/knime-vnc-docker/extensions:/home/developer/.vscode/extensions 
      ## ==== Use current directory as root for mapping Volumes ====
      ## (You need to manually create those child directory: ./data, ./workspace, ./.vscode/extensions)
      - ./app:/home/developer/app
      - ./data:/home/developer/data
      - ./workspace:/home/developer/workspace
      - ./.vscode/extensions:/home/developer/.vscode/extensions

    ## -------------------------------
    ## -- Change to your specific port
    ## -------------------------------
    ports:
      - "5901:5901"
      - "6901:6901"
      - "18080:8080"

    ## -----------------------------
    ## -- Network setup if needed --
    ## -----------------------------
    # networks:
    #  - dev_network

#networks:
#  dev_network:
#    external:
#      name: dev_network


